issue 3 done
leoperezx/api-clima pull request #9
Opened 2021-05-05 03:44 UTC by leoperezx

lista fix #3

2021-05-05 03:55 UTC, nosoycesaros requested changes
Algunos ajustes recomendados

2021-05-05 03:55 UTC, nosoycesaros commented on public/src/clock.js
> +  return { hora, dia, mes, ano };
Estas lineas se podrían simplificar en un solo `return` así:

```js
return {
  hour: date.getHours(),
  day: date.getDate(),
  month: date.toLocaleString('es-co', { month: 'long' }),
  year: date.getFullYear(),
}
```

También sugiero reemplazar los nombres a inglés

2021-05-05 03:55 UTC, nosoycesaros commented on public/src/clock.js
> +  const info = getmonth();
Podrías usar _desestructuración de objetos_ para obtener todas las variables que necesitas, así:

```js 
const { hour, day, month, year } = getMont() 
```

Lo que te permitiría usar `day` en vez de `info.day`

2021-05-05 03:55 UTC, nosoycesaros commented on public/src/clock.js
> +  const date = new Date();
Sugiero que date se pase cómo parámetro de `getMonth` para que pueda calcular la información basado en cualquier fecha dada. ejemplo:

```js
function getMonth(date) { }
```

2021-05-06 01:11 UTC, leoperezx commented on public/src/clock.js
> +  const info = getmonth();
está lista pero Se hace así:
`const  [  hour, day, month, year ] = getMonth()`
El returm de getMonth() debe ser también con llaves cuadradas "[".

2021-05-06 01:17 UTC, leoperezx commented on public/src/clock.js
> +  const date = new Date();
de acuerdo ... se ve mas "prolijo".

2021-05-06 13:04 UTC, merged